#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include "projectmanager.h"
#include "notificationType.h"
#include "pythonexecutor.h"
#include <QProcessEnvironment>
#include <QDir>
#include <QQmlContext>

int main(int argc, char *argv[])
{

    qputenv("QML_XHR_ALLOW_FILE_READ", "1");
    QGuiApplication app(argc, argv);

    QQmlApplicationEngine engine;

    projectManager projectManager;

    engine.rootContext()->setContextProperty("projectManager", &projectManager);

    const QUrl url(QStringLiteral("qrc:/clap_v1/Main.qml"));
    qmlRegisterUncreatableType<NotificationTypeClass>("notification.type", 1, 0, "NotificationTypeClass", "Not creatable as it is an enum type");
    qmlRegisterType<PythonExecutor>("python.executor", 1, 0, "PythonExecutor");

    // Retrieve absolute path of Data/ directory, use it to read file generated by python scripts
    QString dataDirectoryPath = QDir::cleanPath(QCoreApplication::applicationDirPath() + "/../../Data/");
    engine.rootContext()->setContextProperty("dataDirectoryPath", dataDirectoryPath);

    QObject::connect(
        &engine,
        &QQmlApplicationEngine::objectCreationFailed,
        &app,
        []() { QCoreApplication::exit(-1); },
        Qt::QueuedConnection);
    engine.load(url);

    if (engine.rootObjects().isEmpty())
        return -1;

    return app.exec();
}
