import QtQuick

QtObject {

    property var codeIso: [
        { "code": "af", "language": "Afrikaans", "lang": "Afrikaans" },
        { "code": "ar", "language": "Arabic", "lang": "Arabe" },
        { "code": "bg", "language": "Bulgarian", "lang": "Bulgare" },
        { "code": "bn", "language": "Bengali", "lang": "Bengali" },
        { "code": "ca", "language": "Catalan", "lang": "Catalan" },
        { "code": "cs", "language": "Czech", "lang": "Tchèque" },
        { "code": "cy", "language": "Welsh", "lang": "Gallois" },
        { "code": "da", "language": "Danish", "lang": "Danois" },
        { "code": "de", "language": "German", "lang": "Allemand" },
        { "code": "el", "language": "Greek", "lang": "Grec" },
        { "code": "en", "language": "English", "lang": "Anglais" },
        { "code": "es", "language": "Spanish", "lang": "Espagnol" },
        { "code": "et", "language": "Estonian", "lang": "Estonien" },
        { "code": "fa", "language": "Persian", "lang": "Persan" },
        { "code": "fi", "language": "Finnish", "lang": "Finnois" },
        { "code": "fr", "language": "French", "lang": "Français" },
        { "code": "gu", "language": "Gujarati", "lang": "Gujarati" },
        { "code": "he", "language": "Hebrew", "lang": "Hébreu" },
        { "code": "hi", "language": "Hindi", "lang": "Hindi" },
        { "code": "hr", "language": "Croatian", "lang": "Croate" },
        { "code": "hu", "language": "Hungarian", "lang": "Hongrois" },
        { "code": "id", "language": "Indonesian", "lang": "Indonésien" },
        { "code": "it", "language": "Italian", "lang": "Italien" },
        { "code": "ja", "language": "Japanese", "lang": "Japonais" },
        { "code": "kn", "language": "Kannada", "lang": "Kannada" },
        { "code": "ko", "language": "Korean", "lang": "Coréen" },
        { "code": "lt", "language": "Lithuanian", "lang": "Lituanien" },
        { "code": "lv", "language": "Latvian", "lang": "Letton" },
        { "code": "mk", "language": "Macedonian", "lang": "Macédonien" },
        { "code": "ml", "language": "Malayalam", "lang": "Malayalam" },
        { "code": "mr", "language": "Marathi", "lang": "Marathi" },
        { "code": "ne", "language": "Nepali", "lang": "Népalais" },
        { "code": "nl", "language": "Dutch", "lang": "Néerlandais" },
        { "code": "no", "language": "Norwegian", "lang": "Norvégien" },
        { "code": "pa", "language": "Panjabi", "lang": "Panjabi" },
        { "code": "pl", "language": "Polish", "lang": "Polonais" },
        { "code": "pt", "language": "Portuguese", "lang": "Portugais" },
        { "code": "ro", "language": "Romanian", "lang": "Roumain" },
        { "code": "ru", "language": "Russian", "lang": "Russe" },
        { "code": "sk", "language": "Slovak", "lang": "Slovaque" },
        { "code": "sl", "language": "Slovenian", "lang": "Slovène" },
        { "code": "so", "language": "Somali", "lang": "Somali" },
        { "code": "sq", "language": "Albanian", "lang": "Albanais" },
        { "code": "sv", "language": "Swedish", "lang": "Suédois" },
        { "code": "sw", "language": "Swahili", "lang": "Swahili" },
        { "code": "ta", "language": "Tamil", "lang": "Tamoul" },
        { "code": "te", "language": "Telugu", "lang": "Télougou" },
        { "code": "th", "language": "Thai", "lang": "Thaï" },
        { "code": "tl", "language": "Tagalog", "lang": "Tagalog" },
        { "code": "tr", "language": "Turkish", "lang": "Turc" },
        { "code": "uk", "language": "Ukrainian", "lang": "Ukrainien" },
        { "code": "ur", "language": "Urdu", "lang": "Ourdou" },
        { "code": "vi", "language": "Vietnamese", "lang": "Vietnamien" },
        { "code": "zh-cn", "language": "Chinese Simplified", "lang": "Chinois simplifié" }
      ]

}
